---
- name: Ping all hosts
  hosts: all
  gather_facts: yes
  tasks:
    - name: Ping the machine
      ansible.builtin.ping:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
